name: Deploy Static Site to K3s

on:
  push:
    branches:
      - deploy_to_prod

jobs:
  deploy:
    runs-on: self-hosted
    env:
      KUBECONFIG: /home/githubrunner/.kube/config

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image >> 
        run: docker build -t static-site:latest .

      - name: Save image as tar
        run: docker save static-site:latest -o /tmp/static-site.tar

      - name: Import image into K3s containerd
        run: sudo k3s ctr images import /tmp/static-site.tar

      - name: Apply Kubernetes manifest
        run: kubectl apply -f k8s/prod/static-site-prod.yaml

      - name: Restart deployment
        run: kubectl rollout restart deployment/static-site -n prod

      - name: Wait for rollout
        run: kubectl rollout status deployment/static-site -n prod --timeout=180s